version: '3.9'

services:
  app:
    build: .
    ports:
      - "3000:3000" # Пробрасываем порт 3000
    volumes:
      - .:/usr/src/app # Монтируем текущую папку для разработки
    restart: always # Автоматический перезапуск контейнера
